### ISSUE TITLE
Default Title & Description & Image

### ISSUE THREAD

**Issue by ArtemKolichenkov** [xsahil03x/giffy_dialog#44]
Should there be default Title and Description?  
I get that it sounds a bit weird at first but consider following situations where title can be empty:
- Some dynamically generated dialogs where this could easily happen.
- In case of mistake - if something goes wrong it is much better to display neutral title (or empty string) rahter than red screen of death.
- Maybe somebody wants weird dialog box without any text - just some kind of image/animation

Also the case of null image could be handled better. Displaying nothing or some placeholder is better than crashing people's apps.

**Comment by astralstriker** [comment]
Unlike exceptions, which terminate the flow of the program, the Red Screen of Death represents an "Error" thrown by the framework to let the developer know that there is something wrong with their code and they need to fix it. These errors can but should not be caught. It is okay to have those pop up.

@xsahil03x  has already used @required annotation on the named params to ensure that lint ensures that developer doesn't forget adding those fields. 

For those weird name/text- less dialogs, it would be better if you create a factory constructor instead of making the params in the default constructor, optional.

**Comment by xsahil03x** [comment]
@all-contributors please add @astralstriker for question

**Comment by xsahil03x** [comment]
@ArtemKolichenkov I agree with all the points which @astralstriker mentioned above. For the placeholder part, I don't think anyone would have come to this package if he doesn't have any gif to show in dialog in the first place.
